version: '3.1'
services:
  flask:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: api-qrcode
    image: python_api_qrcode
    volumes:
      - ./:/app
    networks:
      - api-qrcode
    ports:
      - 8080:5000
networks:
  api-qrcode:
